---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: search_engine
    component: ui
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  # type: LoadBalancer
  # ports:
  # - port: 80
  #   nodePort: 32092
  #   protocol: TCP
  #   targetPort: 8000
  selector:
    app: search_engine
    component: ui
