---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search_engine
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      name: rabbitmq
      labels:
        app: search_engine
        component: rabbitmq
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository_tag }}"
        name: rabbitmq
        env:
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
