---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search_engine
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.externalPort }}
  - name: amqp
    protocol: TCP
    port: {{ .Values.service.internalPort }}
  selector:
    app: search_engine
    component: rabbitmq
    release: {{ .Release.Name }}
