apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
type: Opaque
data:
  runner-registration-token: "R1IxMzQ4OTQxSmF4MTRFeXhDQzIxVEZwREdIck4=" #echo -n 'GR1348941Jax14EyxCC21TFpDGHrN' | base64
  runner-token: ""
