apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
type: Opaque
data:
  runner-registration-token: "R1IxMzQ4OTQxb2E0eWVFTXRqa1lCeWFzZnN0ZHE=" #echo -n 'GR1348941oa4yeEMtjkYByasfstdq' | base64
  runner-token: ""
