apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
type: Opaque
data:
  runner-registration-token: "R1IxMzQ4OTQxeWZ5UkxXNjMxY19MM2NHNTM3cmI=" #echo -n 'GR1348941yfyRLW631c_L3cG537rb' | base64
  runner-token: ""
