version: '3'
services:

  fluentd:
    image: 123344555/fluentd:4.0
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    networks:
      - back_net
      - front_net

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:${VERSION_ELASTICSEARCH}
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net
      - front_net

  kibana:
    image: kibana:${VERSION_KIBANA}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - back_net
      - front_net

networks:
  front_net:
  back_net:
