apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui-pod
      labels:
        app: search_engine
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: ui
          env:
            - name: MONGO
              value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
