---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  # type: LoadBalancer
  # ports:
  # - port: 80
  #   nodePort: 32092
  #   protocol: TCP
  #   targetPort: 8000
  selector:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
