---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "comment.fullname" . }}
  labels:
    app: search_engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search_engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: crawler
          env:
            - name: MONGO
              value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
            - name: RMQ_HOST
              value: {{ .Values.rabbitmqHost | default (printf "%s-rabbitmq" .Release.Name) }}
            - name: RMQ_QUEUE
              value: queue
            - name: RMQ_USERNAME
              value: guest
            - name: RMQ_PASSWORD
              value: guest
            - name: EXCLUDE_URLS
              value: ".*github.com"
            - name: URL
              value: "https://vitkhab.github.io/search_engine_test_site/"
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
