---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "comment.fullname" . }}
  labels:
    app: search_engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search_engine
    component: crawler
    release: {{ .Release.Name }}
