# This is a basic workflow to help you get started with Actions

name: CI
env:
  COMPOSE_PROJECT_NAME : search_engine
  USERNAME : 123344555
  UI_SERVICE_VERSION : 1.0
  CRAWLER_SERVICE_VERSION : 1.0
  VERSION_MONGO : 3.2
  VERSION_RABBITMQ : 3.9

  VERSION_PROMETHEUS : 1.0
  VERSION_NODE_EXPORTER : 0.15.2
  VERSION_BLACKBOX_EXPORTER : 0.23.0
  VERSION_MONGODB_EXPORTER : 0.36.0

  VERSION_ELASTICSEARCH : 7.6.0
  VERSION_KIBANA : 7.6.0
  VERSION_FLUENT : 4.0

  MONGO_PORT : 27017
  UI_PORT : 8000

  RABBITMQ_DEFAULT_USER : guest
  RABBITMQ_DEFAULT_PASS : guest

  CHECK_INTERVAL : 60
  EXCLUDE_URLS : .*github.com
  URL : 'https://vitkhab.github.io/search_engine_test_site/'  

# Controls when the workflow will run
on: 
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
