# This is a basic workflow to help you get started with Actions

name: CI
env:
  COMPOSE_PROJECT_NAME : search_engine

# Controls when the workflow will run
on: 
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout / Git clone repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.12.8


